# fly.toml app configuration file generated for opportunity-job-mj09mw on 2025-09-22T21:53:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'opportunity-job-mj09mw'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
